### ISSUE TITLE
App does not work with Launcher

### ISSUE THREAD

**Issue by warpech** [handsoncode-apps/BasketDemoApp#3]
An icon and app name is missing. Probably because old app name convention is used.

See screenshots:

![screenshot 2015-11-10 20 00 34](https://cloud.githubusercontent.com/assets/566463/11072376/d9933838-87e5-11e5-8a19-25fa0bff020b.png)

![screenshot 2015-11-10 20 00 40](https://cloud.githubusercontent.com/assets/566463/11072381/dd5f7044-87e5-11e5-8fd2-3bb128600190.png)

**Comment by jakubklekota** [comment]
fixed

**Comment by warpech** [comment]
Still the same problem. Did you test your solution? Your file is using CamelCase names for the properties, whereas Launcher expects lowercase. Compare:

https://github.com/StarcounterSamples/People/blob/master/src/People/ViewModels/AppName.json
https://github.com/handsoncode-apps/Basket/blob/master/Basket/ViewModels/AppName.json
